CREATE TABLE `avis` (
  `xwo_id` bigint(20) NOT NULL,
  `avis_id` varchar(255) DEFAULT NULL,
  `avis_date` datetime DEFAULT NULL,
  `avis_session_id` varchar(255) DEFAULT NULL,
  `avis_api_key` varchar(255) DEFAULT NULL,
  `avis_demarche` varchar(255) DEFAULT NULL,
  `avis_modalite` varchar(255) DEFAULT NULL,
  `avis_score` int(11) DEFAULT NULL,
  `avis_vote` varchar(255) DEFAULT NULL,
  `avis_vote_input` longtext DEFAULT NULL,
  `avis_facile` int(11) DEFAULT NULL,
  `avis_comprehensible` int(11) DEFAULT NULL,
  `avis_autre_difficulte` varchar(255) DEFAULT NULL,
  `avis_autre_aide` varchar(255) DEFAULT NULL,
  `avis_email` varchar(255) DEFAULT NULL,
  `avis_source` varchar(255) DEFAULT NULL,
  `avis_autre` longtext DEFAULT NULL,
  PRIMARY KEY (`xwo_id`),
  KEY `id_idx` (`avis_id`),
  KEY `date_idx` (`avis_date`),
  KEY `facile_idx` (`avis_facile`),
  KEY `demarche_idx` (`avis_demarche`),
  KEY `sessionid_idx` (`avis_session_id`),
  KEY `apikey_idx` (`avis_api_key`),
  KEY `score_idx` (`avis_score`),
  KEY `comprehensible_idx` (`avis_comprehensible`),
  KEY `source_idx` (`avis_source`),
  KEY `modalite_idx` (`avis_modalite`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
